name: update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libglpk-dev

      - name: Install R.
        uses: r-lib/actions/setup-r@v2
        with:
          extra-repositories: https://community.r-multiverse.org
          use-public-rspm: true

      - name: Install helper R package.
        run: |
          install.packages("pak")
          pak::pkg_install("r-multiverse/multiverse.internals@*release")
        shell: Rscript {0}

      - name: Check out the topics repository.
        uses: actions/checkout@v4

      - name: Update topics
        run: |
          multiverse.internals::update_topics(
            path = getwd(),
            repo = "https://community.r-multiverse.org"
          )
        shell: Rscript {0}

      - name: Commit and push changes.
        run: |
          git add *.html
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git config --global user.name github-actions
            git config --global user.email actions@github.com
            git commit -m "Update package status"
            git push -u origin main
          fi
